{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ib3d2pkqrbcqvgrer5hgwodf34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.50"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.50"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.50"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT.jar",
          "size": 4815,
          "sha512": "c490f950ba46a0aeced3729a910d2224c9d02b05885514d38dc1171b39452227b8317082c31b43c69041d084edd80827e2fc36f8a9ee616e9f50c443b2a8a39d",
          "sha256": "75c1a6bdfc1e17c44304cc50775ae6b7fe6d6bb0c36f01428e0b5dd173b24e9e",
          "sha1": "b76df9befea2a7484dc702abcc76c52006744e27",
          "md5": "c217fffb951f54eb76f1db302e1c43b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.50"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.50"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.50"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT.jar",
          "size": 4815,
          "sha512": "c490f950ba46a0aeced3729a910d2224c9d02b05885514d38dc1171b39452227b8317082c31b43c69041d084edd80827e2fc36f8a9ee616e9f50c443b2a8a39d",
          "sha256": "75c1a6bdfc1e17c44304cc50775ae6b7fe6d6bb0c36f01428e0b5dd173b24e9e",
          "sha1": "b76df9befea2a7484dc702abcc76c52006744e27",
          "md5": "c217fffb951f54eb76f1db302e1c43b4"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT.jar",
          "size": 4815,
          "sha512": "c490f950ba46a0aeced3729a910d2224c9d02b05885514d38dc1171b39452227b8317082c31b43c69041d084edd80827e2fc36f8a9ee616e9f50c443b2a8a39d",
          "sha256": "75c1a6bdfc1e17c44304cc50775ae6b7fe6d6bb0c36f01428e0b5dd173b24e9e",
          "sha1": "b76df9befea2a7484dc702abcc76c52006744e27",
          "md5": "c217fffb951f54eb76f1db302e1c43b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.6.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT.jar",
          "size": 4815,
          "sha512": "c490f950ba46a0aeced3729a910d2224c9d02b05885514d38dc1171b39452227b8317082c31b43c69041d084edd80827e2fc36f8a9ee616e9f50c443b2a8a39d",
          "sha256": "75c1a6bdfc1e17c44304cc50775ae6b7fe6d6bb0c36f01428e0b5dd173b24e9e",
          "sha1": "b76df9befea2a7484dc702abcc76c52006744e27",
          "md5": "c217fffb951f54eb76f1db302e1c43b4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.6.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT-javadoc.jar",
          "size": 4761,
          "sha512": "58a1323b1f9c15db3f4f52cc72f10190e09447f6afab7c2702e3a3ded3156313719175636deb434948a40f5f19f48ff98abfd7ed63d3cf354b6af3e3bc56a79d",
          "sha256": "f220ae7bec875d32c710af43dd2881ac12fa3819095439ac11100a70bb12f368",
          "sha1": "ad5878e4db6aea338e9ddd13e3c18cdd8e5db59f",
          "md5": "8cbefe17cbdc10bf01c08f7fe6662944"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-tomcat-2.6.0-SNAPSHOT-sources.jar",
          "size": 4760,
          "sha512": "be51d1d263a5ba967ad4fd486ed57d44700ce83d53cec5abc6d27513eb880efe0e6b528369b4c73cc9d1ad1defb3f84cbac8618f77dcd5568b9bf3995f04db0e",
          "sha256": "6150104862b3617fb699a27bd892120bc360ace38e9ba2f517af8e4c1fc8e7b5",
          "sha1": "23e7dbec12571cf21ef52153b98fb0bb5f1508b0",
          "md5": "5e3d7777b731139ab74857485c741a9a"
        }
      ]
    }
  ]
}
