{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "5.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "glk34wm5ergk3nv4f5amzydqa4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.9.jar",
          "url": "spring-web-5.3.9.jar",
          "size": 1599307,
          "sha512": "4d5a82d873486304f20b0f7cb85e58dfb7eeb2f3dcdcbf83d4473c04a4d71386e8f779146904f52b01a92083761f1e2716e91122e5aab442f0a4863b47100493",
          "sha256": "c8f11853b18f46d30a1bd263eec8de30efafaba5acfa412a2e62ea082b3aaa62",
          "sha1": "88c920ec1bda67fea04daa8e16165777440df473",
          "md5": "da5279d25d36b18f599829f5723d338c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.9"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-web-5.3.9.jar",
          "url": "spring-web-5.3.9.jar",
          "size": 1599307,
          "sha512": "4d5a82d873486304f20b0f7cb85e58dfb7eeb2f3dcdcbf83d4473c04a4d71386e8f779146904f52b01a92083761f1e2716e91122e5aab442f0a4863b47100493",
          "sha256": "c8f11853b18f46d30a1bd263eec8de30efafaba5acfa412a2e62ea082b3aaa62",
          "sha1": "88c920ec1bda67fea04daa8e16165777440df473",
          "md5": "da5279d25d36b18f599829f5723d338c"
        }
      ]
    }
  ]
}
