{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "ib3d2pkqrbcqvgrer5hgwodf34"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.9"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "size": 4788,
          "sha512": "0044e606652fd071c65e38f9ea46155e53af350d1b935695645738869faf61369178eb87e1159ed102e9bf9105d6597bd022ad3199d8900c351a451976f0acf0",
          "sha256": "10e53987641d4dc01d5751b30875d77383c1bc8eaf5a104303a31157ee50e801",
          "sha1": "52d090ed0ecbebea567fb7cd2730d606b7308ab9",
          "md5": "0cfd369c0ee77ed15a09d0c7b0302f5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.9"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "size": 4788,
          "sha512": "0044e606652fd071c65e38f9ea46155e53af350d1b935695645738869faf61369178eb87e1159ed102e9bf9105d6597bd022ad3199d8900c351a451976f0acf0",
          "sha256": "10e53987641d4dc01d5751b30875d77383c1bc8eaf5a104303a31157ee50e801",
          "sha1": "52d090ed0ecbebea567fb7cd2730d606b7308ab9",
          "md5": "0cfd369c0ee77ed15a09d0c7b0302f5f"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "size": 4788,
          "sha512": "0044e606652fd071c65e38f9ea46155e53af350d1b935695645738869faf61369178eb87e1159ed102e9bf9105d6597bd022ad3199d8900c351a451976f0acf0",
          "sha256": "10e53987641d4dc01d5751b30875d77383c1bc8eaf5a104303a31157ee50e801",
          "sha1": "52d090ed0ecbebea567fb7cd2730d606b7308ab9",
          "md5": "0cfd369c0ee77ed15a09d0c7b0302f5f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "size": 4788,
          "sha512": "0044e606652fd071c65e38f9ea46155e53af350d1b935695645738869faf61369178eb87e1159ed102e9bf9105d6597bd022ad3199d8900c351a451976f0acf0",
          "sha256": "10e53987641d4dc01d5751b30875d77383c1bc8eaf5a104303a31157ee50e801",
          "sha1": "52d090ed0ecbebea567fb7cd2730d606b7308ab9",
          "md5": "0cfd369c0ee77ed15a09d0c7b0302f5f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT-javadoc.jar",
          "size": 4756,
          "sha512": "0bc9ca6ea2a28f86ab43581e8415d7eff1db8a2b1b3a57cb7efc0e4dcb1acb4e9066fa194c01f6daef6875e1684b4a5daf2a8bec9ad97b563fa0bc0df2767132",
          "sha256": "5bf07b5c0f5410b403819d1f5d0c01623e07f3d8bc889c9ffbccc619f83279d1",
          "sha1": "ea642a22b58125319d85322cb32f8de8c64c75f2",
          "md5": "18dcbfc7e349c9eb1d17283d36d8eb26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT-sources.jar",
          "size": 4754,
          "sha512": "b50adc632ecde58a6bad14a7634347257bf132be27a717cf842cc56df026aeca956d8c4db2ff896fde1cfc163535e2511bc8bb624db9f0e8b6d2d602616b622d",
          "sha256": "17d4e629257f2216eef1f40850099c0b8525f95cbd7c573a041fa3435686b371",
          "sha1": "abcdbaeba19d13c683cc8aa6720d6d1637ed8e29",
          "md5": "c6ec2723bf810eeecbd3f5edff524593"
        }
      ]
    }
  ]
}
