{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "e2mf6smaxzfs5naqmqcw2bj5we"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.9-SNAPSHOT"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "size": 4788,
          "sha512": "39ed54b9ed1f99928592f480f05caa385b6c2f57c3a62e6079d582bdb3a53a712627e46b00952d963de53a0fd291c365a748daffc00fb2189ea1287473d3dc4c",
          "sha256": "2cd6de99d7527d3e692c8f5c3de556c3e2ea76e69404fc809410f9c159b1c766",
          "sha1": "09dfb12532b4ccca1aff43b45596f8adc8041225",
          "md5": "ddcdc8deafcdfc61daf5a03b659c35a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.0-SNAPSHOT"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.9-SNAPSHOT"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "size": 4788,
          "sha512": "39ed54b9ed1f99928592f480f05caa385b6c2f57c3a62e6079d582bdb3a53a712627e46b00952d963de53a0fd291c365a748daffc00fb2189ea1287473d3dc4c",
          "sha256": "2cd6de99d7527d3e692c8f5c3de556c3e2ea76e69404fc809410f9c159b1c766",
          "sha1": "09dfb12532b4ccca1aff43b45596f8adc8041225",
          "md5": "ddcdc8deafcdfc61daf5a03b659c35a0"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "size": 4788,
          "sha512": "39ed54b9ed1f99928592f480f05caa385b6c2f57c3a62e6079d582bdb3a53a712627e46b00952d963de53a0fd291c365a748daffc00fb2189ea1287473d3dc4c",
          "sha256": "2cd6de99d7527d3e692c8f5c3de556c3e2ea76e69404fc809410f9c159b1c766",
          "sha1": "09dfb12532b4ccca1aff43b45596f8adc8041225",
          "md5": "ddcdc8deafcdfc61daf5a03b659c35a0"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT.jar",
          "size": 4788,
          "sha512": "39ed54b9ed1f99928592f480f05caa385b6c2f57c3a62e6079d582bdb3a53a712627e46b00952d963de53a0fd291c365a748daffc00fb2189ea1287473d3dc4c",
          "sha256": "2cd6de99d7527d3e692c8f5c3de556c3e2ea76e69404fc809410f9c159b1c766",
          "sha1": "09dfb12532b4ccca1aff43b45596f8adc8041225",
          "md5": "ddcdc8deafcdfc61daf5a03b659c35a0"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT-javadoc.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT-javadoc.jar",
          "size": 4756,
          "sha512": "137e8c6788ead1047597992f1be9e856f1b392d103e4c166c5dd052ecf4c3f5810b8aca11b26956397e8927dbee35a6679bc95f1b9015be5a2124f49e995f3ab",
          "sha256": "f593f71ed5b3bce52353e3b7f9dc7eb9d5568fb5faf30125191ca132ba67517a",
          "sha1": "3c610d5423dc401a8ee24a6d129911ff9a4407a0",
          "md5": "cef7c3c0ab399df2ec75d20a4e7d7e65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.0-SNAPSHOT-sources.jar",
          "url": "spring-boot-starter-2.6.0-SNAPSHOT-sources.jar",
          "size": 4754,
          "sha512": "a5d0a7b3ec745caabde9d9cb7895ab18f891c59b733ba1c34fc768315f634376705f11f5ae12851916426a50d248705f46762909fb694a02ef39daf1bc3db57a",
          "sha256": "a53c55a0eaa53844a76d787c365d1e3ccc06bfa41deb4b65241c6b64dc56999b",
          "sha1": "1d4f7428822b384ff63ef5e79bedb8b7d6d153b5",
          "md5": "66458963a633f987538c4d25e3aa09dc"
        }
      ]
    }
  ]
}
